---
title: "trade"
author: "Ryan Zhang"
date: "2022-12-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(tidymodels)
library(rstanarm)
library(Hmisc)
library(corrplot)
library(dplyr)
library(data.table) 
library(scales)
library(ggplot2)
```

## Import Trade Data

```{r}
# Clean China trade data

china <- read_csv(file = "trade_data/china_trade_2019.csv") %>%
  subset(select = c("Partner Name",
                    "Export (US$ Thousand)", 
                    "Import (US$ Thousand)")) %>%
  rename("Imports from China ($)" = "Export (US$ Thousand)",
         "Exports to China ($)" = "Import (US$ Thousand)",
         "Country" = "Partner Name") %>%
  mutate("Exports and Imports with China ($)" = 
           rowSums(.[, c("Imports from China ($)", "Exports to China ($)")]))

# Clean Taiwan trade data 

taiwan <- read_csv(file = "trade_data/taiwan_trade_2019.csv") %>%
  subset(select = c("Partner Name",
                    "Export (US$ Thousand)", 
                    "Import (US$ Thousand)")) %>%
  rename("Imports from Taiwan ($)" = "Export (US$ Thousand)",
         "Exports to Taiwan ($)" = "Import (US$ Thousand)",
         "Country" = "Partner Name") %>%
  mutate("Exports and Imports with Taiwan ($)" = 
           rowSums(.[, c("Imports from Taiwan ($)", "Exports to Taiwan ($)")]))

# Clean world trade data

world <- read_csv(file = "trade_data/world_trade_2019.csv") %>%
  subset(select = c("Partner Name", "Year", 
                    "Export (US$ Thousand)", 
                    "Import (US$ Thousand)")) %>%
  rename("Total Exports ($)" = "Export (US$ Thousand)",
         "Total Imports ($)" = "Import (US$ Thousand)",
         "Country" = "Partner Name") %>%
  mutate("Total Exports and Imports ($)" = 
           rowSums(.[, c("Total Exports ($)", "Total Imports ($)")]))

# Combine China, Taiwan, and world trade data

final <- inner_join(world, china, by = "Country") %>%
  inner_join(., taiwan, by = "Country") %>%
  
  # Calculate each country's trade with China and Taiwan as a fraction of total trade
  
  mutate(`Exports and Imports with China (%)` = 
           `Exports and Imports with China ($)` / 
              `Total Exports and Imports ($)` * 100,
              `Exports and Imports with Taiwan (%)` = 
           `Exports and Imports with Taiwan ($)` / 
              `Total Exports and Imports ($)` * 100)

# Export the final data table 

write.csv(final, "trade_data/final_trade_2019.csv", row.names = FALSE)
```